var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(e,f,g){e!=Array.prototype&&e!=Object.prototype&&(e[f]=g.value)};$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(e,f,g,d){if(f){g=$jscomp.global;e=e.split(".");for(d=0;d<e.length-1;d++){var a=e[d];a in g||(g[a]={});g=g[a]}e=e[e.length-1];d=g[e];f=f(d);f!=d&&null!=f&&$jscomp.defineProperty(g,e,{configurable:!0,writable:!0,value:f})}};$jscomp.underscoreProtoCanBeSet=function(){var e={a:!0},f={};try{return f.__proto__=e,f.a}catch(g){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(e,f){e.__proto__=f;if(e.__proto__!==f)throw new TypeError(e+" is not extensible");return e}:null;$jscomp.polyfill("Object.setPrototypeOf",function(e){return e||$jscomp.setPrototypeOf},"es6","es5");
var __extends=this&&this.__extends||function(){var e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,g){e.__proto__=g}||function(e,g){for(var d in g)g.hasOwnProperty(d)&&(e[d]=g[d])};return function(f,g){function d(){this.constructor=f}e(f,g);f.prototype=null===g?Object.create(g):(d.prototype=g.prototype,new d)}}(),sys;
(function(e){e.$1=function(a){return"undefined"!==typeof a};e.$2=function(a){return"function"===typeof a};e.$3=function(a){return"string"===typeof a};e.$4=function(a,b){return b&&"none"!=b&&"#"!=b.charAt(0)?0==a?b.substring(1):"#"+b:b};e.$5=function(a){for(var b=[],c=1;c<arguments.length;c++)b[c-1]=arguments[c];var d=window;a&&d.setTimeout(function(){a&&a.apply(d,b)},0)};e.$6=function(a,b){b=b||{d:null};b.b=b.b||"POST";var c=new XMLHttpRequest;c.open(b.b,a,!0);b.a||"POST"!=b.b?b.a(c):c.setRequestHeader("Content-Type",
"application/x-www-form-urlencoded");c.send(b.d);c.onreadystatechange=function(){4==c.readyState&&(b.c&&b.c(c,c.response),c=null)}};var f=function(){function a(){}Object.defineProperty(a.prototype,"_",{get:function(){return this},enumerable:!0,configurable:!0});a.prototype.$=function(a){return a.bind(this)};return a}();e.xObject=f;var g=function(a){function b(b){var c=a.call(this)||this;c.y=b;return c}__extends(b,a);Object.defineProperty(b.prototype,"x",{get:function(){var a=this._;a.z||(a.z=a.y());
return a.z},enumerable:!0,configurable:!0});return b}(f);e.Lazy=g;var d=function(a){function b(b){var c=a.call(this)||this;c.w=b||new Function;return c}__extends(b,a);b.prototype.a=function(){var a=this._;a.z&&a.v||(a.v=a.x?a.x():new (Function.prototype.bind.apply(a.w,[{}].concat(a.y?a.y():[]))));return a.v};b.prototype.b=function(a){this.x=a;return this};b.prototype.c=function(a){this.y=a;return this};Object.defineProperty(b.prototype,"d",{get:function(){this.z=!0;return this},enumerable:!0,configurable:!0});
return b}(f);e.Bean=d;f=function(){function a(){}a.y=function(b,c){var h=new d(b);console.log(c?c:b.toString());return a.z[c?c:window.btoa(b.toString())]=h};a.x=function(b){var c="#";e.$2(b)?c=window.btoa(b.toString()):"string"==typeof b&&(c=b);return(b=a.z[c])?b.a():null};a.z={};return a}();e.Pod=f;f=function(){function a(){}a.a=function(){return document.body};a.b=function(){return document.documentElement};a.c=function(b,c){c=c||a.a();c.appendChild(b);return c};a.d=function(b){var c=window;if(b)return b.getBoundingClientRect();
b=a.a();var d=a.b();return{left:0,top:0,right:(c.innerWidth||d.clientWidth||b.clientWidth)-1,bottom:(c.innerHeight||d.clientHeight||b.clientHeight)-1,height:0,width:0}};a.e=function(a){return document.getElementById(a)};a.f=function(a,c,d){e.$1(d)?a.setAttribute(c,d):a.removeAttribute(c)};a.g=function(a,c){a.style.cssText=c};a.h=function(a,c){a=document.createElement(a);c&&(a.className=c);return a};a.i=function(b,c,d,e){if(c&&d&&e){b=a.y[b%2]+"EventListener";for(var g=0;g<d.length;g++)c[b](a.z[d[g]],
e[g])}};a.j=function(b,c,d){d=a.d(d||a.b());return b>=d.left&&b<=d.right&&c>=d.top&&c<=d.bottom};a.k=function(b,c,d){d&&c&&d.forEach(function(d){c.classList[a.y[b%2]](d)})};a.l=function(a,c){return a&&a.classList.contains(c)};a.m=function(b,c){return(c||a.b()).querySelectorAll(b)};a.n=function(a){return(new e.Svg("svg")).a(a).t};a.o=function(b,c,d){var e=a.d();return 2==b?"right:"+(e.right-c)+"px;top:"+d+"px;":3==b?"left:"+c+"px;bottom:"+(e.bottom-d)+"px;":5==b?"right:"+(e.right-c)+"px;bottom:"+(e.bottom-
d)+"px;":"left:"+c+"px;top:"+d+"px;"};a.z="mousewheel mousedown mouseup mousemove mouseleave click hidden context change keydown".split(" ");a.y=["add","remove"];return a}();e.Html=f;f=function(a){function b(c,d){var e=a.call(this)||this;e.t=d;e.u=b.x(c);d&&d.appendChild(e.u);return e}__extends(b,a);b.z=function(){return"http://www.w3.org/2000/svg"};b.y=function(){return"http://www.w3.org/1999/xlink"};b.x=function(a){return document.createElementNS(b.z(),a)};b.w=function(a,b,d,e){void 0===e&&(e=null);
a.setAttributeNS(e,b,d)};b.prototype.a=function(a){var c=new b("use",this.u);b.w(c.u,"xlink:href","#"+a,b.y());return c};return b}(e.xObject);e.Svg=f})(sys||(sys={}));var ui;
(function(e){var f=function(e){function d(a,b){var c=e.call(this)||this;c.z=[];a&&a.z.push(c);c.x=b||{};c.w=a;return c}__extends(d,e);Object.defineProperty(d.prototype,"v",{get:function(){var a=this._;a.y||a.u(sys.Html);return a.y},enumerable:!0,configurable:!0});d.prototype.u=function(a){var b=this._;b.y&&(b.z.forEach(function(c){a.c(c.v,b.y)}),b.m(b,b.x))};d.prototype.t=function(a){var b=this._,c=b.x;["c","d","e","g","h"].forEach(function(b){sys.$1(a[b])&&(c[b]=a[b])});b.y&&b.m(b,c)};d.prototype.s=
function(a){var b=this.z;a=b.indexOf(a);0<=a&&b.splice(a,1)};d.prototype.r=function(a){var b=this._;for(b.w&&b.w.s(b);0<b.z.length;)b.z[0].r(a)};d.prototype.q=function(a){var b=this._,c=b.y;if(c)return sys.$1(a)&&c.hidden!=a&&(c.hidden=a,b.z.forEach(function(b){return b.q(a)}),c.dispatchEvent(new CustomEvent("hidden",{detail:b}))),c.hidden};d.prototype.p=function(a){var b=this._;b.x.f&&(a?sys.Html.c(b.y):b.y.remove())};d.prototype.o=function(a,b,c){var d=sys.Html,e=this._,g=e.x.f;if(g){var f=e.v;
d.g(f,d.o(c||0,a,b));d.k(0,f,["_xpopup"]);g.$5(e)}};d.prototype.n=function(){var a=this.x.f;a&&a.$6()};d.prototype.m=function(a,b){a.y.disabled=!!b.d;a.y.hidden=!!b.e;b.a&&(a.y.dataset.id=b.a)};return d}(sys.xObject);e.Control=f;f=function(e){function d(a){a=e.call(this,null,a)||this;a.$0=[];var b=sys.Html;a.y=b.h("div","_xmodal");a.$4(a,b);return a}__extends(d,e);d.prototype.$4=function(a,b){a.y.hidden=!0;a.$1=[a.$(a.$8)];a.$3=[a.$(a.$9),a.$(a.x2)];a.$2=[a.$(a.$7)];b.c(a.y)};d.prototype.$5=function(a,
b){var c=sys.Html,d=this._;c.k([1,0][Number(!!b)],d.y,["_xmask"]);c.i(0,a.v,[6],d.$2);a.q(!1)};d.prototype.$6=function(){this.$0.forEach(function(a){return a.q(!0)})};d.prototype.$7=function(a){var b=sys.Html,c=this._;a.detail.q()?(a=c.$0.pop(),0==c.$0.length&&(c.x1(b),b.i(1,a.v,[6],c.$2),a.r(b))):(c.$0.push(a.detail),1==c.$0.length&&c.x0(b))};d.prototype.$8=function(a){27==a.keyCode&&(a.stopPropagation(),a=this.$0,0<a.length&&a[a.length-1].q(!0))};d.prototype.$9=function(a){var b=!1;this.$0.forEach(function(c){return b=
b||sys.Html.j(a.pageX,a.pageY,c.v)});b||this.$0.forEach(function(a){return a.q(!0)})};d.prototype.x0=function(a){var b=this._;a.i(0,b.y,[1,7],b.$3);a.i(0,a.b(),[9],b.$1);b.q(!1)};d.prototype.x1=function(a){var b=this._;a.i(1,b.y,[1,7],b.$3);a.i(1,a.b(),[9],b.$1);b.q(!0)};d.prototype.x2=function(a){this.$0.forEach(function(a){return a.q(!0)});return!1};return d}(e.Control);e.Modal=f;f=function(e){function d(a,b){a=e.call(this,a,b)||this;a.$0=[a.$(a.$1)];return a}__extends(d,e);d.prototype.u=function(a){var b=
this._,c=b.x;b.y=a.h("button",c.b);c.c&&a.i(0,b.y,[5],b.$0);c.g&&(b.y.innerText=c.g);c.h&&a.f(b.y,"title",c.h);e.prototype.u.call(this,a)};d.prototype.$1=function(a){a.stopPropagation();sys.$5(this.x.c,this)};d.prototype.r=function(a){var b=this._;b.x.c&&a.i(1,b.y,[5],b.$0);e.prototype.r.call(this,a)};return d}(e.Control);e.Button=f;f=function(e){function d(a,b){b=b||{};b.$0=b.$0||"svg";return e.call(this,a,b)||this}__extends(d,e);d.prototype.u=function(a){var b=this._,c=b.x;"svg"==c.$0&&(b.y=a.n(c.i),
c.b&&(b.y.className=c.b))};return d}(e.Control);e.Image=f;f=function(e){function d(a,b){b=b||{};b.$0=b.$0||"span";return e.call(this,a,b)||this}__extends(d,e);d.prototype.u=function(a){var b=this._,c=b.x;b.y=a.h(c.$0,c.b);c.g&&(b.y.innerText=c.g);e.prototype.u.call(this,a)};d.prototype.t=function(a){e.prototype.t.call(this,a);a=this._;a.y&&a.x.g&&(a.y.innerText=a.x.g)};return d}(e.Control);e.Text=f;f=function(e){function d(a,b){return e.call(this,a,b)||this}__extends(d,e);d.prototype.u=function(a){var b=
this._;b.y=a.h("div",b.x.b);b.p(!0);e.prototype.u.call(this,a)};d.prototype.r=function(a){this.p(!1);e.prototype.r.call(this,a)};return d}(e.Control);e.Pane=f;f=function(e){function d(a,b){a=e.call(this,a,b)||this;a.$0=[a.$(a.$1)];return a}__extends(d,e);d.prototype.u=function(a){var b=this._,c=b.x,d=0<c.$2||0<c.$3;b.y=a.h(d?"textarea":"input",c.b);var g=b.y;c.$0&&(g.placeholder=c.$0);c.$1&&(g.maxLength=c.$1);d&&(d=b.y,d.rows=c.$2,d.cols=c.$3);b.x.c&&a.i(0,g,[8],b.$0);c.g&&(g.value=c.g);e.prototype.u.call(this,
a)};d.prototype.t=function(a){e.prototype.t.call(this,a);a=this._;var b=a.y;b&&a.x.g&&(b.value=a.x.g)};d.prototype.$1=function(a){a=this._;sys.$5(a.x.c,a,a.y.value)};d.prototype.r=function(a){var b=this._;b.x.c&&a.i(1,b.y,[8],b.$0);e.prototype.r.call(this,a)};return d}(e.Control);e.Textbox=f;f=function(e){function d(a,b,c){a=e.call(this,a,c)||this;a.$0=b||[];return a}__extends(d,e);d.prototype.u=function(a){var b=this._;b.y=a.h("ul",b.x.b);a.k(0,b.y,["_xlist"]);b.$0.forEach(function(c){b.$2(a,c)});
e.prototype.u.call(this,a)};d.prototype.$2=function(a,b){var c=this._,e=a.h("li",b.b);a.k(0,e,[d.$1]);b.a&&(e.dataset.id=b.a);b.d&&a.c(b.d.v,e);b.c&&(e.hidden=!0);a.c(e,c.y);return e};d.$1="_xlitem";return d}(e.Control);e.List=f;f=function(g){function d(a,b,c){a=g.call(this,a,b,c)||this;a.$00=[a.$(a.$7),a.$(a.$9),a.$(a.$5)];return a}__extends(d,g);d.prototype.u=function(a){g.prototype.u.call(this,a);a.i(0,this.y,[5,4,3],this.$00)};d.prototype.$2=function(a,b){var c=[],d=g.prototype.$2.call(this,a,
b);b.v&&!b.d&&a.c(a.n(b.v),d);b.sd&&c.push("disabled");b.z&&c.push("checked");b.u?c.push("drop"):b.w&&c.push("tip");0<c.length&&a.k(0,d,c);return d};d.prototype.$5=function(a){var b=this._;a=b.x2(a.srcElement);b.$6(b.x3(a),a)};d.prototype.$6=function(a,b){this.x1(a,b)};d.prototype.$7=function(a){var b=this._,c=b.x2(a.srcElement),d=b.x3(c);d&&!d.sd&&sys.Html.l(c,e.List.$1)&&(a.stopPropagation(),b.$8(d,c))};d.prototype.$8=function(a,b){var c=this._;a.u?(b=c.x7(a.t,sys.Html.d(b)),a.u().o(b.left,b.top,
a.t)):sys.$5(a.y?a.y:c.x.c,c,a)};d.prototype.$9=function(a){this.x0()};d.prototype.x0=function(){this.x1()};d.prototype.x1=function(a,b){this.x6(!1,!0);a&&!a.sd&&b&&sys.Html.k(0,b,["on"])};d.prototype.x2=function(a){for(;a&&a.nodeName&&"LI"!=a.nodeName;)a=a.parentElement;return a&&sys.Html.l(a,e.List.$1)?a:null};d.prototype.x3=function(a){for(var b=this.$0,c=0;a&&c<b.length;c++){var d=b[c];if(d.a==a.dataset.id)return d}return null};d.prototype.x6=function(a,b){var c=this._;console.log("uiList::blank - "+
this.x6.caller.toString());[].forEach.call(sys.Html.m("li._xlitem",c.y),function(c){c=c.classList;a&&c.remove("down");b&&c.remove("on")})};d.prototype.x7=function(a,b){return{width:0,height:0,left:2==a||5==a?b.right:b.left,top:3>a?b.bottom:b.top,bottom:0,right:0}};d.prototype.r=function(a){a.i(1,this.y,[5,4,3],this.$00);g.prototype.r.call(this,a)};return d}(e.List);e.Toolist=f;f=function(g){function d(a,b){a=g.call(this,a,b)||this;b=a.$(a.$8);a.$0=a.$6();a.$1=a.$7(b);new e.Text(new e.Button(a,{c:b,
b:"_xdoff"}));a.$5();return a}__extends(d,g);d.prototype.$3=function(a){return new e.Pane(this.$2,{b:"_xdband"+(a?" "+a:"")})};d.prototype.$4=function(){var a=this._,b=a.x;sys.Html.g(a.v,"width:"+b.$1+"px;height:"+b.$0+"px;margin-left:"+-b.$1/2+"px;margin-top:"+3*-b.$0/4+"px");b.f.$5(a,!0)};d.prototype.u=function(a){var b=this._,c=b.x,d=c.a;b.y=a.h("div",c.b);a.k(0,b.y,["_xdlg"]);sys.$1(c.e)&&(b.y.hidden=c.e);b.y.id=d;b.p(!0);g.prototype.u.call(this,a)};d.prototype.$5=function(){this.$2=new e.Pane(this,
{b:"_xdbody"})};d.prototype.$6=function(){var a=this._,b=new e.Pane(a,{b:"_xdtitle"});new e.Text(b,{g:a.x.g});return b};d.prototype.$7=function(a){var b=this._,c=new e.Pane(b,{b:"_xdfoot"});new e.Button(c,{c:a,g:b.x.$3});return c};d.prototype.$8=function(a){this.q(!0)};d.prototype.r=function(a){this.p(!1);g.prototype.r.call(this,a)};return d}(e.Control);e.Dialog=f;f=function(g){function d(a,b){var c=g.call(this,a,b)||this;c.$1="E6D0DE CDA2BE B5739D E1D5E7 C3ABD0 A680B8 D4E1F5 A9C4EB 7EA6E0 D5E8D4 9AC7BF 67AB9F D5E8D4 B9E0A5 97D077 FFF2CC FFE599 FFD966 FFF4C3 FFCE9F FFB570 F8CECC F19C99 EA6B66".split(" ");
c.$2="none FFFFFF E6E6E6 CCCCCC B3B3B3 999999 808080 666666 4D4D4D 333333 1A1A1A 000000 FFCCCC FFE6CC FFFFCC E6FFCC CCFFCC CCFFE6 CCFFFF CCE5FF CCCCFF E5CCFF FFCCFF FFCCE6 FF9999 FFCC99 FFFF99 CCFF99 99FF99 99FFCC 99FFFF 99CCFF 9999FF CC99FF FF99FF FF99CC FF6666 FFB366 FFFF66 B3FF66 66FF66 66FFB3 66FFFF 66B2FF 6666FF B266FF FF66FF FF66B3 FF3333 FF9933 FFFF33 99FF33 33FF33 33FF99 33FFFF 3399FF 3333FF 9933FF FF33FF FF3399 FF0000 FF8000 FFFF00 80FF00 00FF00 00FF80 00FFFF 007FFF 0000FF 7F00FF FF00FF FF0080 CC0000 CC6600 CCCC00 66CC00 00CC00 00CC66 00CCCC 0066CC 0000CC 6600CC CC00CC CC0066 990000 994C00 999900 4D9900 009900 00994D 009999 004C99 000099 4C0099 990099 99004D 660000 663300 666600 336600 006600 006633 006666 003366 000066 330066 660066 660033 330000 331A00 333300 1A3300 003300 00331A 003333 001933 000033 190033 330033 33001A".split(" ");
a=c.x;c.$6=a.$2;c.$5=[c.$(c.x2)];c.$4=new e.Pane(c,{b:"_xhex"});console.log("Color::constructor - "+a.$2);c.$3=new e.Textbox(c.$4,{$1:6,g:a.$2});new e.Button(c.$4,{g:a.$1,c:function(){return c.x1(c.$3.v.value)}});return c}__extends(d,g);d.prototype.u=function(a){var b=this._,c=b.x,e=a.h("div",c.b);b.y=e;a.k(0,e,["_xcolor"]);for(var f=b.$8(a,"T1"),k=0;2>k;k++)a.c(b.$7(a,c,b.$1,12*k),f);a.c(f,e);f=b.$8(a,"T2");for(k=0;10>k;k++)a.c(b.$7(a,c,b.$2,12*k),f);a.c(f,e);f=b.$8(a,"T3");b.x4=b.$7(a,c,d.$0,0);
a.c(b.x4,f);a.c(f,e);a.c(b.$4.v,e);a.i(0,b.y,[5],b.$5);b.p(!0);g.prototype.u.call(this,a)};d.prototype.$7=function(a,b,c,d){for(var e=a.h("tr"),g=0;12>g;g++){var f=a.h("td"),h=c[d+g];h&&(f.style.backgroundColor="#"+h,f.dataset.color=h);"noop"==h&&b.$3&&a.f(f,"title",b.$3);h&&"n"==h.charAt(0)&&(a.c(a.h("span"),f),f.className=h);a.c(f,e)}return e};d.prototype.$8=function(a,b){a=a.h("table");a.cellSpacing="0";a.id=b;return a};d.prototype.$9=function(a){for(;a&&a.nodeName&&"TD"!=a.nodeName;)a=a.parentElement;
return a};d.prototype.x0=function(a){var b=d.$0;-1==b.indexOf(a)&&(12==b.length&&b.splice(1,1),b.push(a))};d.prototype.x1=function(a){var b=this._;b.$6!=a&&(b.$6=a,sys.$5(b.x.c,b,b.$6));b.n()};d.prototype.x2=function(a){var b=this._,c=b.$9(a.srcElement);c&&(a.stopPropagation(),a=c.dataset.color,"noop"==a?b.x5():("none"!=a&&b.x0(a),b.x1(a)))};d.prototype.x5=function(){d.$0.splice(1,d.$0.length-1);var a=sys.Html.m("td:not(.noop)",this.x4);[].forEach.call(a,function(a){return a.style.backgroundColor=
""})};d.prototype.t=function(a){g.prototype.t.call(this,a);var b=this.x;b.$2=a.$2;sys.$1(b.$2)&&this.$3.t({g:a.$2})};d.prototype.r=function(a){var b=this._;a.i(1,b.y,[5],b.$5);b.p(!1);g.prototype.r.call(this,a)};d.$0=["noop"];return d}(e.Control);e.Color=f;f=function(f){function d(a,b){a=f.call(this,a,b)||this;b=a.x;a.$1=[a.$(a.$3)];b.$1=sys.$4(0,b.$1);a.$0=[a.$(a.$6)];a.$2=new e.Text(a,{$0:"label"});new e.Text(a,{g:b.g});new e.Text(a,{b:"drop"});return a}__extends(d,f);d.prototype.u=function(a){var b=
this._,c=b.x;b.y=a.h("button",c.b);a.i(0,b.y,[5],b.$0);f.prototype.u.call(this,a);b.$2.v.style.background=sys.$4(1,c.$1);a.k(0,b.y,["_xdropclr"])};d.prototype.$5=function(a,b){var c=a.x;c.$1!=b&&(c.$1=b,a.$2&&(a.$2.v.style.background=sys.$4(1,b)),sys.$5(c.c,a,sys.$4(1,c.$1)))};d.prototype.$6=function(a){var b=this._;a=b.x;var c=a.$0();if(b.$4=c){c.t({$2:a.$1,c:function(a,c){b.$5(b,c)},e:!0});var d=sys.Html.d(b.y);c.o(d.left,d.bottom,a.$2);sys.Html.i(0,c.v,[6],b.$1);sys.Html.k(0,b.y,["on"])}};d.prototype.$3=
function(a){console.log("uiDropColor::onColorHide");a=this._;sys.Html.i(1,a.$4.v,[6],a.$1);sys.Html.k(0,a.y,["on"])};d.prototype.t=function(a){f.prototype.t.call(this,a);var b=this._,c=b.x;sys.$1(a.$1)&&(a=sys.$4(0,a.$1),c.$1!=a&&(c.$1=a,b.$2&&(b.$2.v.style.background=sys.$4(1,a))))};d.prototype.r=function(a){var b=this._;a.i(1,b.y,[5],b.$0);b.$4&&b.$4.q(!0);f.prototype.r.call(this,a)};return d}(e.Control);e.DropColor=f;f=function(f){function d(a,b){a=f.call(this,a,b)||this;a.$00=["inc","dec","hex"];
b=a.x;b.$1=b.$1||Number.MAX_VALUE;b.$2=b.$2||-b.$1;b.$0=b.$0||0;new e.Textbox(a,{c:a.$(a.$03),g:b.$0.toString(),b:a.$00[2]});new e.Button(a,{c:a.$(a.$02),b:a.$00[0]});new e.Button(a,{c:a.$(a.$02),b:a.$00[1]});return a}__extends(d,f);d.prototype.u=function(a){f.prototype.u.call(this,a);a.k(0,this.y,["_xspin"])};d.prototype.$01=function(a){a.$2&&a.$0<a.$2&&(a.$0=a.$2);a.$1&&a.$0>a.$1&&(a.$0=a.$1)};d.prototype.t=function(a){f.prototype.t.call(this,a);var b=this._,c=b.x;b.z.forEach(function(a){a.t({d:c.d})});
a.$0&&(c.$0=a.$0,b.z[0].t({g:c.$0.toString()}))};d.prototype.$02=function(a){var b=this._,c=b.x;c.$0>c.$2&&c.$0<c.$1&&(c.$0+=a.x.b==b.$00[0]?1:-1,b.z[0].t({g:c.$0.toString()}),sys.$5(b.x.c,b,c.$0))};d.prototype.$03=function(a,b){a=this._;var c=a.x;b=+b|0;c.$0!=b&&(c.$0=b,a.$01(c),sys.$5(a.x.c,a,c.$0))};return d}(e.Pane);e.Spinner=f;f=function(f){function d(a,b){a=f.call(this,a,b)||this;a.$0=[a.$(a.$1)];new e.Text(new e.Text(a,{b:"out"}),{b:"in"});return a}__extends(d,f);d.prototype.u=function(a){var b=
this._,c=b.x,d=a.h("button",c.b);b.y=d;a.k(0,d,["_xcheck"]);c.h&&a.f(d,"title",c.h);c.$0&&a.k(0,d,["on"]);c.g&&(b.y.dataset.tip=c.g);a.i(0,d,[5],b.$0);f.prototype.u.call(this,a)};d.prototype.$1=function(a){console.log("uiToggle::onClick - "+this.x.$0);a.stopPropagation();this.$2(!this.x.$0)};d.prototype.$2=function(a){var b=this._,c=b.x;if(!sys.$1(a))return c.$0;c.$0=a;sys.$5(c.c,b,a);sys.Html.k([1,0][Number(a)],b.y,["on"])};d.prototype.t=function(a){f.prototype.t.call(this,a);var b=this._,c=this.x;
sys.$1(a.$0)&&(c.$0=a.$0,sys.Html.k([1,0][Number(c.$0)],b.y,["on"]))};d.prototype.r=function(a){var b=this._;a.i(1,b.y,[5],b.$0);f.prototype.r.call(this,a)};return d}(e.Control);e.Toggle=f})(ui||(ui={}));
